/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Homework9 */

#ifndef _Included_Homework9
#define _Included_Homework9
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Homework9
 * Method:    convertCtoF
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_Homework9_convertCtoF
  (JNIEnv *, jobject, jint);

/*
 * Class:     Homework9
 * Method:    roundUp
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_Homework9_roundUp
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
